Init project
wafflestudio19-5/team6-server pull request #1
Opened 2021-11-21 07:31 UTC by pullup-dip-burpee

2021-11-21 08:28 UTC, Gorani9 approved these changes

2021-11-21 08:28 UTC, Gorani9 commented on carrot/src/main/kotlin/waffle/team6/carrot/PingTestController.kt
> +}
확인 했습니다! 머지해도 될 것 같습니다

2021-11-21 10:31 UTC, Gorani9 approved these changes

2021-11-21 10:31 UTC, Gorani9 commented on carrot/src/main/resources/application.yml
> +    password: waffle-team6
database 이름 "carrot"으로 생성했고, username "waffle-team6-server", password "wafflestudio"로 유저 생성했습니다. 반영 부탁드릴게요

2021-11-21 10:37 UTC, Gorani9 requested changes

2021-11-21 10:37 UTC, Gorani9 commented on carrot/src/main/resources/application.yml
> +    password: waffle-team6
database 이름 "carrot"으로 생성했고, username "waffle-team6-server", password "wafflestudio"로 유저 생성했습니다. 반영 부탁드릴게요

2021-11-21 15:01 UTC, pullup-dip-burpee commented on carrot/src/main/resources/application.yml
> +    password: waffle-team6
반영해서 커밋 푸시했습니다

2021-11-22 03:53 UTC, Gorani9 approved these changes

2021-11-24 05:52 UTC, merged