user-6 Feat: Implement user apis
wafflestudio19-5/team6-server pull request #31
Opened 2021-12-30 17:37 UTC by pullup-dip-burpee

- get products
- get likes
- get purchase_requests
- and minor modifications

---
아직 테스트를 안 해봐서 draft PR로 올립니다... 테스트 후 일반 PR로 변경하겠습니다

2022-01-02 15:57 UTC, Gorani9 requested changes
develop rebase하고 수정해서 다시 올려주실 수 있으신가요? Product 쪽에 삭제된 필드가 있네요. 필요하실 판매글, 구매요청, 관심목록 repository 함수 만들어놨습니다. 일단 페이징 해놓긴 했는데 수정하셔도 됩니다

2022-01-02 16:21 UTC, pullup-dip-burpee commented
> develop rebase하고 수정해서 다시 올려주실 수 있으신가요? Product 쪽에 삭제된 필드가 있네요. 필요하실 판매글, 구매요청, 관심목록 repository 함수 만들어놨습니다. 일단 페이징 해놓긴 했는데 수정하셔도 됩니다
> 
> 추가: applications.yml에 이제 서버 ddl update로 해놓아야 할 것 같습니다. 추가해주시면 감사하겠습니다.

넵 알겠습니다! Rebase 해서 conflict 나는거 해결하고 올릴게요!

+ 방금 생각난건데 페이지네이션 구현에 약간 수정이 필요할 것 같습니다. 당근마켓의 경우 무한 스크롤링을 전제하는데, 가령 실시간으로 판매글 리스트에 새로운 내역들이 많이 추가되는 경우를 생각하면, 구매자 입장에서는 판매글 리스트를 천천히 보다가 다음으로 내렸는데, 이미 페이지 번호가 밀려서 이미 본 아이템들이 뜰 수 있습니다. 페이지네이션 쿼리에 마지막으로 본 값의 id를 넣고 그걸로 where 절 조건을 건다거나 하는 작업이 필요할 것 같습니다

2022-01-02 16:23 UTC, Gorani9 commented
> 방금 생각난건데 페이지네이션 구현에 약간 수정이 필요할 것 같습니다. 당근마켓의 경우 무한 스크롤링을 전제하는데, 가령 실시간으로 판매글 리스트에 새로운 내역들이 많이 추가되는 경우를 생각하면, 구매자 입장에서는 판매글 리스트를 천천히 보다가 다음으로 내렸는데, 이미 페이지 번호가 밀려서 이미 본 아이템들이 뜰 수 있습니다. 페이지네이션 쿼리에 마지막으로 본 값의 id를 넣고 그걸로 where 절 조건을 건다거나 하는 작업이 필요할 것 같습니다 

아 네! 이것도 봤는데 너무 단순하게 생각했네요. 다음 PR때 작업해서 올릴겠습니다. 감사합니다 !!

2022-01-03 14:36 UTC, pullup-dip-burpee commented
> develop rebase하고 수정해서 다시 올려주실 수 있으신가요? Product 쪽에 삭제된 필드가 있네요. 필요하실 판매글, 구매요청, 관심목록 repository 함수 만들어놨습니다. 일단 페이징 해놓긴 했는데 수정하셔도 됩니다
> 
> 추가: applications.yml에 이제 서버 ddl update로 해놓아야 할 것 같습니다. 추가해주시면 감사하겠습니다.

수정했습니다!

2022-01-03 14:43 UTC, Gorani9 approved these changes
LGTM, 특별히 리뷰할 게 없네요

2022-01-03 14:43 UTC, Gorani9 commented on carrot/src/main/kotlin/waffle/team6/carrot/user/api/UserController.kt
> +    @GetMapping("/me/purchase_requests/")
URI에 보통 _대신 -를 쓰는 것으로 알고 있습니다! 찾아보니 밑줄이나 하이퍼링크가 걸린 경우 언더바가 잘 안보이는 이유때문이라고 합니다

2022-01-03 14:43 UTC, Gorani9 commented on carrot/src/main/resources/application.yml
> +      ddl-auto: update
감사합니다!!

2022-01-03 15:11 UTC, pullup-dip-burpee commented on carrot/src/main/kotlin/waffle/team6/carrot/user/api/UserController.kt
> +    @GetMapping("/me/purchase_requests/")
감사합니다! 수정했습니다 :)

2022-01-03 15:34 UTC, merged